"""Учебные направления и главы внутри каждого.

Содержание построено по research-источникам:
- Product track: CIRCLES (Comprehend, Identify customer, Report needs,
  Cut, List, Evaluate, Summarize) + типы PM-кейсов (Design / Improvement /
  Growth / Strategy / Estimation / RCA), стандарт PM-собеседований FAANG.
- Business track: классические консалтинговые типы (Profitability,
  Market Entry, Pricing, M&A, Growth) + Issue Tree / MECE, Market Sizing,
  экономика и финальная рекомендация — стандарт McKinsey / BCG / Bain.
"""

PRODUCT_TRACK_CHAPTERS = [
    {
        "id": "p_clarify",
        "title": "Clarify the prompt",
        "circle": "C — Comprehend",
        "summary": "Уточни цель, контекст, продукт и пользователя до того, как генерировать идеи.",
        "skills": ["Clarifying questions", "Goal alignment", "Constraints"],
        "outcome": "Сформулирован goal в формате метрика + сегмент + горизонт.",
        "stepIds": ["clarify_objective", "case_archetype"],
    },
    {
        "id": "p_user",
        "title": "User & JTBD",
        "circle": "I — Identify customer",
        "summary": "Выбери primary user, опиши JTBD, контекст и pain points.",
        "skills": ["Personas", "JTBD", "User context"],
        "outcome": "1 primary user, 2-3 jobs, ranked pain points.",
        "stepIds": ["product_approach", "segmentation"],
    },
    {
        "id": "p_needs",
        "title": "Pain points & opportunities",
        "circle": "R — Report needs",
        "summary": "Преврати наблюдения о пользователе в проверяемые problem statements.",
        "skills": ["Problem statement", "Insight → opportunity"],
        "outcome": "Список pain points с severity и frequency.",
        "stepIds": ["cjm", "root_cause_analysis"],
    },
    {
        "id": "p_prioritize",
        "title": "Prioritization",
        "circle": "C — Cut through",
        "summary": "Отбери проблемы и решения по impact / effort, RICE, MoSCoW.",
        "skills": ["RICE", "Impact / effort", "Trade-offs"],
        "outcome": "1-2 проблемы выбраны с явным критерием.",
        "stepIds": ["initiatives"],
    },
    {
        "id": "p_solutions",
        "title": "Solution design",
        "circle": "L — List solutions",
        "summary": "Сгенерируй 3+ решения, опиши MVP и пользовательский сценарий.",
        "skills": ["Ideation", "MVP scoping", "User flow"],
        "outcome": "3 решения, выбран one MVP с обоснованием.",
        "stepIds": ["product_design", "ai_ml"],
    },
    {
        "id": "p_tradeoffs",
        "title": "Trade-offs & metrics",
        "circle": "E — Evaluate",
        "summary": "Опиши NSM, guardrail-метрики, эксперимент и trade-offs.",
        "skills": ["NSM", "Guardrails", "A/B test design"],
        "outcome": "NSM + 2 guardrail + дизайн эксперимента.",
        "stepIds": ["metrics", "experiments"],
    },
    {
        "id": "p_summary",
        "title": "Recommendation & next step",
        "circle": "S — Summarize",
        "summary": "Дай executive-ответ, риски, roadmap, первый шаг на 2 недели.",
        "skills": ["Executive summary", "Risks", "Roadmap"],
        "outcome": "Рекомендация в 3 предложениях + первый шаг.",
        "stepIds": ["risks", "roadmap", "final_synthesis", "reflection"],
    },
]

BUSINESS_TRACK_CHAPTERS = [
    {
        "id": "b_case_condition",
        "title": "Условие кейса и задача клиента",
        "circle": "01 · Intake",
        "summary": "Отдели факты условия от интерпретаций: кто клиент, что случилось, какой вопрос надо решить.",
        "definition": "Условие кейса — это вводная задача клиента: контекст, данные, ограничения и decision question. На этом этапе нельзя решать; нужно точно зафиксировать, что спрашивают.",
        "terms": [
            {"name": "Client objective", "meaning": "Измеримая цель клиента: прибыль, рост, доля рынка, снижение затрат, запуск или выбор стратегии."},
            {"name": "Decision question", "meaning": "Главный вопрос, на который должна ответить рекомендация: стоит ли делать, что выбрать, почему и при каких условиях."},
            {"name": "Constraint", "meaning": "Ограничение по срокам, бюджету, регуляторике, ресурсам, бренду или операционным возможностям."},
        ],
        "methodMaterials": [
            "Перепиши вводную в формате: клиент -> проблема -> цель -> ограничения -> данные -> вопрос.",
            "Отмечай, что является фактом из условия, а что является твоим допущением.",
            "Если цель звучит расплывчато, превращай её в метрику, горизонт и критерий успеха.",
        ],
        "skills": ["Problem restatement", "Objective function", "Decision criteria"],
        "outcome": "Короткий бриф кейса: цель, ограничения, данные и критерий решения.",
        "stepIds": ["clarify_objective"],
    },
    {
        "id": "b_archetype",
        "title": "Тип кейса и маршрут решения",
        "circle": "02 · Route",
        "summary": "Определи тип задачи: прибыль, рост, выход на рынок, pricing, M&A, RCA или запуск.",
        "definition": "Тип кейса задаёт логику анализа: какие ветки строить первыми, какие данные искать и какой критерий решения будет главным.",
        "terms": [
            {"name": "Profitability case", "meaning": "Задача про прибыль: разложить выручку и затраты, найти драйвер изменения."},
            {"name": "Market entry", "meaning": "Решение о входе на рынок: привлекательность рынка, право на победу, экономика и риски."},
            {"name": "Pricing case", "meaning": "Выбор цены через ценность для клиента, затраты, конкурентов, эластичность и стратегию."},
        ],
        "methodMaterials": [
            "Сначала классифицируй кейс, затем выбери 2-3 главные ветки анализа.",
            "Для decision case заранее запиши критерий: ROI, срок окупаемости, риск, стратегическое соответствие.",
            "Не перечисляй все фреймворки подряд: выбери маршрут, который отвечает на вопрос клиента.",
        ],
        "skills": ["Case archetypes", "Framework selection"],
        "outcome": "Тип кейса + базовая структура анализа.",
        "stepIds": ["case_archetype"],
    },
    {
        "id": "b_tree",
        "title": "Issue Tree, MECE и гипотезы",
        "circle": "03 · Structure",
        "summary": "Разложи проблему на MECE-ветки, добавь драйверы и проверяемые гипотезы.",
        "definition": "Issue tree — дерево вопросов или драйверов, которое превращает большую задачу в проверяемые блоки анализа без пересечений и пробелов.",
        "terms": [
            {"name": "MECE", "meaning": "Mutually exclusive, collectively exhaustive: ветки не пересекаются и вместе покрывают задачу."},
            {"name": "Driver tree", "meaning": "Дерево метрики, где результат раскладывается на факторы: цена, объём, конверсия, частота, затраты."},
            {"name": "Hypothesis", "meaning": "Проверяемое предположение, которое можно подтвердить или опровергнуть данными."},
        ],
        "methodMaterials": [
            "Начинай дерево от главного вопроса, а не от любимого фреймворка.",
            "На каждом листе дерева должно быть понятно, какие данные нужны для проверки.",
            "Формулируй гипотезы как причинно-следственные утверждения, а не как идеи решений.",
        ],
        "skills": ["MECE", "Driver tree", "Hypotheses"],
        "outcome": "Дерево 3-5 веток с гипотезами и нужными данными.",
        "stepIds": ["issue_tree"],
    },
    {
        "id": "b_market",
        "title": "Рынок, отрасль и конкуренты",
        "circle": "04 · Outside-in",
        "summary": "Размер рынка, тренды, конкуренты, value chain, revenue / cost drivers.",
        "definition": "Outside-in анализ проверяет внешний контекст: есть ли спрос, кто конкурирует, где создаётся ценность и какие внешние силы влияют на решение.",
        "terms": [
            {"name": "Value chain", "meaning": "Цепочка создания ценности: поставщики, производство, каналы, продажи, сервис, удержание."},
            {"name": "Porter 5F", "meaning": "Пять сил конкуренции: конкуренты, покупатели, поставщики, заменители, новые игроки."},
            {"name": "Market attractiveness", "meaning": "Оценка рынка по размеру, росту, маржинальности, конкуренции и барьерам входа."},
        ],
        "methodMaterials": [
            "Каждый рыночный факт должен менять решение: сегмент, цену, канал, риск или сроки.",
            "Сравни клиента с конкурентами по предложению, цене, каналам, unit economics и бренду.",
            "Разделяй тренды, которые уже влияют на P&L, и слабые сигналы, которые пока являются риском.",
        ],
        "skills": ["Market sizing", "Porter 5F", "Value chain"],
        "outcome": "Sizing с диапазоном + 2-3 ключевых вывода.",
        "stepIds": ["research"],
    },
    {
        "id": "b_market_sizing",
        "title": "Market sizing и расчёт допущений",
        "circle": "05 · Sizing",
        "summary": "Посчитай порядок величины рынка, спроса, клиентов, операций или выручки.",
        "definition": "Market sizing — оценка масштаба через прозрачную формулу и допущения, когда точных данных недостаточно.",
        "terms": [
            {"name": "Top-down", "meaning": "Расчёт от большой базы: население или рынок -> сегменты -> penetration -> частота -> объём."},
            {"name": "Bottom-up", "meaning": "Расчёт от единицы: один клиент, магазин, рейс или заказ -> количество единиц -> общий объём."},
            {"name": "Sanity check", "meaning": "Проверка результата на здравый смысл: порядок величины, сравнение с известными данными или мощностью."},
        ],
        "methodMaterials": [
            "Всегда называй базу, сегменты, допущения, формулу, диапазон и sanity check.",
            "Лучше дать диапазон и чувствительное допущение, чем одно точное число без объяснения.",
            "После расчёта объясни, что число значит для решения: стоит ли рынок внимания и при каких условиях.",
        ],
        "skills": ["Top-down", "Bottom-up", "Assumption tree", "Sanity check"],
        "outcome": "Расчёт масштаба с формулой, диапазоном и проверкой порядка величины.",
        "stepIds": ["market_sizing"],
    },
    {
        "id": "b_customer",
        "title": "Клиенты, сегменты и CJM",
        "circle": "06 · Customer",
        "summary": "Выбери приоритетные сегменты, JTBD, путь клиента, pain points и bottlenecks.",
        "definition": "Клиентский анализ показывает, для кого создаётся решение, где возникает боль и какой участок пути клиента даёт максимальный эффект.",
        "terms": [
            {"name": "Segment", "meaning": "Группа клиентов с похожей потребностью, поведением, экономикой или каналом покупки."},
            {"name": "JTBD", "meaning": "Job To Be Done: задача, которую клиент пытается выполнить с помощью продукта или сервиса."},
            {"name": "Bottleneck", "meaning": "Узкое место воронки или пути клиента, где теряется непропорционально много ценности."},
        ],
        "methodMaterials": [
            "Сегментируй по потребности, поведению, прибыльности и доступности, а не только по демографии.",
            "В CJM для каждого этапа укажи цель клиента, touchpoint, pain point, метрику и возможную причину потери.",
            "Выбор сегмента должен быть связан с экономикой: LTV, CAC, маржа, риск, скорость запуска.",
        ],
        "skills": ["Segmentation", "JTBD", "CJM", "Funnel analysis"],
        "outcome": "Приоритетный сегмент, карта пути клиента и ключевой bottleneck.",
        "stepIds": ["segmentation", "cjm"],
    },
    {
        "id": "b_diagnosis",
        "title": "Диагностика root cause",
        "circle": "07 · Diagnose",
        "summary": "Найди корневую причину через дерево метрик, сегменты, change log и сравнения.",
        "definition": "Root cause analysis отделяет симптом от причины: сначала нужно доказать, где и почему сломалась метрика, и только потом предлагать решения.",
        "terms": [
            {"name": "Metric tree", "meaning": "Разложение метрики на драйверы: выручка = клиенты × ARPU, прибыль = выручка - затраты."},
            {"name": "Segment isolation", "meaning": "Поиск проблемы через сравнение сегментов, каналов, регионов, категорий или периодов."},
            {"name": "Change log", "meaning": "Список изменений продукта, операций, цен, каналов или рынка перед началом проблемы."},
        ],
        "methodMaterials": [
            "Покажи, где просадка есть и где её нет; это быстрее ведёт к причине.",
            "Ищи изменение перед началом проблемы: цены, каналы, ассортимент, SLA, алгоритмы, конкуренты.",
            "Не предлагай инициативы, пока не назван механизм причины и способ его проверить.",
        ],
        "skills": ["Metric tree", "Root cause", "5 Whys", "Segment isolation"],
        "outcome": "Подтверждённая root cause и данные, которыми её можно проверить.",
        "stepIds": ["root_cause_analysis"],
    },
    {
        "id": "b_solution_portfolio",
        "title": "Портфель инициатив и приоритизация",
        "circle": "08 · Solve",
        "summary": "Сгенерируй варианты решения, свяжи их с root cause и выбери приоритеты.",
        "definition": "Инициатива — конкретное действие, которое меняет драйвер проблемы. Сильный портфель покрывает несколько механизмов влияния и имеет понятный trade-off.",
        "terms": [
            {"name": "Impact / effort", "meaning": "Быстрая оценка ценности и сложности инициативы."},
            {"name": "RICE", "meaning": "Фреймворк Reach, Impact, Confidence, Effort для приоритизации продуктовых и бизнес-инициатив."},
            {"name": "Trade-off", "meaning": "Компромисс между скоростью, стоимостью, риском, качеством, брендом или масштабом."},
        ],
        "methodMaterials": [
            "Каждая инициатива должна ссылаться на конкретную причину или драйвер из дерева.",
            "Для 3-5 инициатив укажи impact, effort, риск, владельца и быстрый тест.",
            "Не выбирай самую красивую идею; выбирай ту, которая лучше проходит критерий решения клиента.",
        ],
        "skills": ["Initiative design", "Impact / effort", "RICE", "Trade-offs"],
        "outcome": "Приоритизированный набор инициатив с логикой выбора.",
        "stepIds": ["product_design", "initiatives"],
    },
    {
        "id": "b_gtm",
        "title": "Go-To-Market и операционная реализация",
        "circle": "09 · Launch",
        "summary": "Опиши сегмент запуска, позиционирование, каналы, партнёров и фазы внедрения.",
        "definition": "GTM отвечает на вопрос, как решение попадёт к клиенту и начнёт менять бизнес-метрики в реальной операционной системе.",
        "terms": [
            {"name": "Beachhead", "meaning": "Первый узкий сегмент, где проще доказать ценность перед масштабированием."},
            {"name": "Positioning", "meaning": "Обещание ценности относительно альтернатив: почему клиент выберет именно это решение."},
            {"name": "Operating model", "meaning": "Люди, процессы, системы и партнёры, которые нужны для исполнения стратегии."},
        ],
        "methodMaterials": [
            "Покажи фазы запуска: подготовка, пилот, запуск, масштабирование, оптимизация.",
            "Свяжи каналы с сегментами: B2B sales, партнёры, digital, офлайн, CRM, комьюнити.",
            "Добавь операционные зависимости: команда, IT, обучение, SLA, юридические требования, supply chain.",
        ],
        "skills": ["GTM", "Positioning", "Channel strategy", "Operating model"],
        "outcome": "План запуска с сегментом, каналами, фазами и зависимостями.",
        "stepIds": ["go_to_market", "roadmap"],
    },
    {
        "id": "b_metrics_validation",
        "title": "Метрики, эксперименты и валидация",
        "circle": "10 · Validate",
        "summary": "Задай success metrics, guardrails, тест гипотезы и критерий остановки.",
        "definition": "Валидация показывает, как команда поймёт, что решение работает, и какие сигналы нельзя ухудшать ради роста главной метрики.",
        "terms": [
            {"name": "North Star Metric", "meaning": "Главная метрика ценности, которую продукт или бизнес создаёт для клиентов и компании."},
            {"name": "Guardrail metric", "meaning": "Защитная метрика, которую нельзя ухудшить: маржа, churn, NPS, риск, SLA, fraud."},
            {"name": "MVP / Pilot", "meaning": "Ограниченный запуск, который проверяет главную гипотезу до масштабирования."},
        ],
        "methodMaterials": [
            "Для каждой инициативы назови leading indicator и lagging business metric.",
            "Формулируй эксперимент как H0/H1, аудитория, метод, длительность, метрики и критерий успеха.",
            "Если есть AI/ML, отдельно проверь данные, baseline, качество модели, product KPI и риски.",
        ],
        "skills": ["NSM", "Guardrails", "Experiment design", "AI/ML fit"],
        "outcome": "Метрики успеха, guardrails и план проверки гипотез.",
        "stepIds": ["metrics", "experiments", "ai_ml"],
    },
    {
        "id": "b_economics",
        "title": "Экономика, финмодель и sensitivity",
        "circle": "11 · Economics",
        "summary": "Посчитай CAC, LTV, payback, ROI, break-even и чувствительность допущений.",
        "definition": "Финансовая модель переводит стратегию в деньги: сколько инициатива стоит, какие драйверы меняет, когда окупается и где решение ломается.",
        "terms": [
            {"name": "Unit economics", "meaning": "Экономика одной единицы: клиента, заказа, транзакции, магазина, рейса или подписки."},
            {"name": "Payback", "meaning": "Срок, за который инвестиции или CAC возвращаются через маржу или денежный поток."},
            {"name": "Sensitivity analysis", "meaning": "Проверка, как результат меняется при ухудшении ключевых допущений."},
        ],
        "methodMaterials": [
            "Свяжи P&L с инициативами: что меняем, сколько это стоит, какую метрику двигает и когда окупится.",
            "Покажи базовый, оптимистичный и консервативный сценарии.",
            "Обязательно проверь главное допущение на -20% или +20% и объясни устойчивость вывода.",
        ],
        "skills": ["Unit economics", "ROI", "Break-even", "Sensitivity"],
        "outcome": "Финансовый вывод с диапазоном, payback и чувствительными допущениями.",
        "stepIds": ["economics"],
    },
    {
        "id": "b_risks",
        "title": "Риски, ограничения и митигация",
        "circle": "12 · Risks",
        "summary": "Разложи риски по вероятности и влиянию, добавь ранние индикаторы и планы снижения.",
        "definition": "Риск-анализ показывает, что может нарушить рекомендацию, как это заметить заранее и что сделать, чтобы снизить ущерб.",
        "terms": [
            {"name": "Probability / impact", "meaning": "Оценка риска по вероятности наступления и силе влияния на результат."},
            {"name": "Mitigation", "meaning": "Действие, которое снижает вероятность или ущерб риска."},
            {"name": "Early indicator", "meaning": "Ранний сигнал, по которому команда поймёт, что риск начинает реализовываться."},
        ],
        "methodMaterials": [
            "Раздели риски на market, financial, operational, product, legal, reputational и execution.",
            "Для топ-3 рисков дай owner, early indicator и конкретный mitigation.",
            "Покажи, какие риски меняют рекомендацию, а какие просто требуют контроля.",
        ],
        "skills": ["Risk register", "Mitigation", "Early indicators"],
        "outcome": "Топ-риски с приоритетом, сигналами и планом митигации.",
        "stepIds": ["risks"],
    },
    {
        "id": "b_recommend",
        "title": "Финальная рекомендация и защита",
        "circle": "13 · Land",
        "summary": "Собери вывод по Pyramid Principle: рекомендация, 3 аргумента, экономика, риски, next step.",
        "definition": "Финальная рекомендация — это не пересказ анализа, а управленческий ответ: что делать, почему, какой эффект, какие условия и первый шаг.",
        "terms": [
            {"name": "Pyramid Principle", "meaning": "Коммуникация сверху вниз: главный вывод -> аргументы -> доказательства."},
            {"name": "Executive summary", "meaning": "Краткий ответ для руководителя: решение, эффект, риски, условия и следующий шаг."},
            {"name": "Next step", "meaning": "Конкретное действие на ближайший период: пилот, расчёт, интервью, запуск, due diligence."},
        ],
        "methodMaterials": [
            "Начинай с ответа, а не с истории анализа.",
            "Дай 2-3 доказательства: рынок, клиентская причина, экономика, риски, реализация.",
            "Заканчивай первым шагом на 2-4 недели и тем, что нужно проверить перед масштабированием.",
        ],
        "skills": ["Pyramid principle", "Executive summary", "Roadmap", "Reflection"],
        "outcome": "1-page recommendation + next step и личный разбор ошибок.",
        "stepIds": ["final_synthesis", "reflection"],
    },
]

TRACKS = [
    {
        "id": "product",
        "name": "Продуктовые кейсы",
        "tagline": "PM-собеседования: FAANG, Яндекс, Авито, Tinkoff",
        "description": (
            "Структурированный подход CIRCLES к задачам design / improvement / "
            "growth / strategy. Отрабатывается логика продуктового мышления: от "
            "пользователя и JTBD до метрик, экспериментов и финальной рекомендации."
        ),
        "duration": "7 глав · ~90 минут практики",
        "chapters": PRODUCT_TRACK_CHAPTERS,
    },
    {
        "id": "business",
        "name": "Бизнес-кейсы",
        "tagline": "Консалтинг и кейс-чемпионаты: McKinsey, BCG, Bain, Changellenge",
        "description": (
            "Классическая консалтинговая воронка: тип кейса → issue tree → рынок → "
            "диагностика → инициативы → экономика → рекомендация. Готовит к "
            "интервью в стратегические консалтинговые фирмы и к финалам кейс-чемпионатов."
        ),
        "duration": "13 глав · ~150 минут практики",
        "chapters": BUSINESS_TRACK_CHAPTERS,
    },
]
